version: 0.2

env:
  variables:
    RUBY_VERSION: '2.7.4'
    DATABASE_URL: 'awseb-e-ze8ipv2mwm-stack-awsebrdsdatabase-i9fj95a8jlso.ciob878rraz8.us-west-2.rds.amazonaws.com'
    DATABASE_USERNAME: 'alexnaughton'
    DATABASE_PASSWORD: '5deJeans!'

phases: 
  install:
    commands:
      - echo Installing dependencies...........
      - apt-get update -y
      - apt-get install -y build-essential libpq-dev nodejs
      - rbenv install $RUBY_VERSION
      - rbenv global $RUBY_VERSION
  pre_build: 
    commands:
      - echo Installing gems...
      - bundle install
  build:
    commands:
      - echo Migrating and seeding db...
      - bundle exec rake db:create
      - bundle exec rake db:migrate
      - bundle exec rake db:seed