version: 0.2

env:
  variables:
    RUBY_VERSION: '2.7.4'

phases: 
  install:
    commands:
      - echo Installing dependencies...........
      - apt-get update -y
      - apt-get install -y ruby-dev build-essential libpq-dev nodejs
  pre_build: 
    commands:
      - echo Installing gems...
      - bundle install
  build:
    commands:
      - echo Migrating and seeding db...
      - bundle exec rake db:migrate
      - bundle exec rake db:seed